services:
  db-backup:
    build:
      context: .
    container_name: db-backup
    volumes:
      - Backups:/Backups
    networks:
      - global-network

volumes:
  Backups:

networks:
  global-network:
    external: true
